import type { Metadata } from "next";
import { site } from "./site";

/** Generated by app/opengraph-image.tsx. */
export const shareImage = { url: "/opengraph-image", width: 1200, height: 630, alt: `${site.name} — ${site.tagline}` };

/**
 * Complete metadata for an interior page. Next.js merges metadata shallowly,
 * so a page that sets `openGraph` replaces the layout's entirely — this helper
 * always emits the full set (Open Graph + Twitter + canonical) so no page
 * inherits the homepage's title, URL, or share text.
 */
export function pageMetadata({ title, description, path }: { title: string; description: string; path: string }): Metadata {
  const fullTitle = `${title} | ${site.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: "en_US",
      url: path,
      title: fullTitle,
      description,
      images: [shareImage],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [shareImage.url] },
  };
}

/** schema.org BreadcrumbList from the same crumbs shown on the page. */
export function breadcrumbJsonLd(crumbs: { label: string; href?: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.label,
      ...(c.href && { item: new URL(c.href, site.url).toString() }),
    })),
  };
}
